[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'GmsCore support'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change header'"
excluded-patches = "'GmsCore support'"
patcher-args = "-Oheader=premium*header "

