enable-magisk-update = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "module"
arch = "arm64-v8a"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "'Change header'"
patcher-args = "-Oheader=premium*header "
